version: "3.8"

services:
  booking:
    build:
      context: .
      dockerfile: mcp/servers/booking/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      -
  places:
    build:
      context: .
      dockerfile: mcp/servers/places/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - .:/app

  trip_planner:
    build:
      context: .
      dockerfile: mcp/servers/trip_planner/Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - .:/app

  weather:
    build:
      context: .
      dockerfile: mcp/servers/weather/Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - .:/app
